libs =
#import libs += libhello%lib{hello}

./: exe{polymorphic-protocol}: libue{polymorphic-protocol}: {hxx ixx txx cxx}{** -**.test...} $libs
exe{polymorphic-protocol}: testscript

# Unit tests.
#
exe{*.test}:
{
  test = true
  install = false
}

for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n}
  $d/exe{$n}: libue{polymorphic-protocol}: bin.whole = false
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
